name: build-artifacts

on: [ push, pull_request ]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: checkout repository
      uses: actions/checkout@v3
    - name: Archive Release
      uses: thedoctor0/zip-release@master
      with:
        filename: "夕夜Craft材质包.zip"
        exclusions: "*.git* *.yml"
    - name: Upload build artifacts
      uses: actions/upload-artifact@v1
      with:
        name: build-artifacts
        path: 夕夜Craft材质包.zip