name: optimize-PNG-files

on:
  push:
    branches:
      - main
    paths:
      - '**/*.png'

jobs:
  build:
    name: Optimize PNG files
    runs-on: ubuntu-latest
    steps:
      - name: Get latest code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Install oxipng
        uses: baptiste0928/cargo-install@v1
        with:
          crate: oxipng
          version: latest

      - name: Get changed PNG files
        id: changed-files
        uses: tj-actions/changed-files@v23.2
        with:
          since_last_remote_commit: "true"
          files: '**/*.png'

      - name: Optimize PNG files
        run: oxipng -sZ -o 3 -i 0 --ng ${{ steps.changed-files.outputs.all_changed_files }}
      
      - name : Get optimized PNG files
        id: optimized-files
        run: echo "::set-output name=all_optimized_files::$(git status --porcelain | sed s/^...// | sed -z 's/\n/%0A/g;s/%0A$/\n/')"
      
      - name: Commit and push changes
        if: ${{ steps.optimized-files.outputs.all_optimized_files }}
        uses: swinton/commit@v2.x
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            ${{ steps.optimized-files.outputs.all_optimized_files }}
          commit-message: '优化PNG文件'
          ref: ${{ github.ref }}